---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mfs-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

stages:
  - name: jj
    from: docker.io/library/rust
    modules:
      - type: script
        snippets:
          - apt-get update 
          - cargo install --locked --bin jj jj-cli
          - mkdir -p /out/ && mv $CARGO_HOME/bin/jj /out/jj
          - /out/jj util completion fish > /out/jj.fish

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: copy
    from: jj
    src: /out/jj
    dest: /usr/bin/

  - type: copy
    from: jj
    src: /out/jj.fish
    dest: /usr/share/fish/completions/

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: copy
    from: docker.io/creativeprojects/resticprofile:latest
    src: /usr/bin/resticprofile
    dest: /usr/bin/

  - type: copy
    from: ghcr.io/rustic-rs/rustic:latest
    src: /rustic
    dest: /usr/bin/

  - type: bling
    install:
      - 1password

  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      packages:
        - micro
        - starship
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-gsconnect
        - gnome-tweaks
        - baobab
        - fish
        - podman-compose
        - setroubleshoot-server
        - distrobox
        - code
        - bindfs
        - btrbk
        - et
        - gdb
        - intel-gpu-tools
        - ncdu
        - rclone
        - restic
        - yq
        - fd-find
        - gcc
        - zoxide
        - ripgrep
        - wireshark
        - flatpak-builder
        - tealdeer
        - virt-viewer
        - hcloud
        - gitui
        - gh
        - chezmoi
        - p7zip
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox

  - type: default-flatpaks
    configurations:
      - scope: system
        notify: false # Send notification after install/uninstall is finished (true/false)
        install:
          - org.mozilla.firefox
          - com.google.Chrome
          - io.missioncenter.MissionCenter
          - org.gnome.Loupe
          - org.gnome.Showtime
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - org.gnome.TextEditor
          - org.gnome.Calculator
          - org.gnome.Evince
          - com.mattjakeman.ExtensionManager
          - io.github.flattool.Warehouse
          - org.gnome.Boxes
          - org.libreoffice.LibreOffice
      - scope: user
        notify: false
        repo:
          url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          name: flathub-beta
          title: Flathub Beta

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - SourceCodePro
      google-fonts:
        - Open Sans

  - type: justfiles
    validate: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

